/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RedirectsRouteImport } from './routes/redirects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PortfoliosRouteImport } from './routes/portfolios'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PortfoliosPortfolioIdRouteImport } from './routes/portfolios.$portfolioId'
import { Route as PagesPageIdRouteImport } from './routes/pages.$pageId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as MediaMediaIdRouteImport } from './routes/media.$mediaId'
import { Route as CouponsCouponIdRouteImport } from './routes/coupons.$couponId'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectsRoute = RedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosRoute = PortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const PortfoliosPortfolioIdRoute = PortfoliosPortfolioIdRouteImport.update({
  id: '/$portfolioId',
  path: '/$portfolioId',
  getParentRoute: () => PortfoliosRoute,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => PagesRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const MediaMediaIdRoute = MediaMediaIdRouteImport.update({
  id: '/$mediaId',
  path: '/$mediaId',
  getParentRoute: () => MediaRoute,
} as any)
const CouponsCouponIdRoute = CouponsCouponIdRouteImport.update({
  id: '/$couponId',
  path: '/$couponId',
  getParentRoute: () => CouponsRoute,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/navigation': typeof NavigationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pages': typeof PagesRouteWithChildren
  '/portfolios': typeof PortfoliosRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/redirects': typeof RedirectsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/coupons/$couponId': typeof CouponsCouponIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/navigation': typeof NavigationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pages': typeof PagesRouteWithChildren
  '/portfolios': typeof PortfoliosRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/redirects': typeof RedirectsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/coupons/$couponId': typeof CouponsCouponIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/coupons': typeof CouponsRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/navigation': typeof NavigationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pages': typeof PagesRouteWithChildren
  '/portfolios': typeof PortfoliosRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/redirects': typeof RedirectsRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/coupons/$couponId': typeof CouponsCouponIdRoute
  '/media/$mediaId': typeof MediaMediaIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/categories'
    | '/contacts'
    | '/coupons'
    | '/leads'
    | '/login'
    | '/media'
    | '/navigation'
    | '/orders'
    | '/pages'
    | '/portfolios'
    | '/posts'
    | '/products'
    | '/profile'
    | '/redirects'
    | '/settings'
    | '/tags'
    | '/categories/$categoryId'
    | '/coupons/$couponId'
    | '/media/$mediaId'
    | '/orders/$orderId'
    | '/pages/$pageId'
    | '/portfolios/$portfolioId'
    | '/posts/$postId'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/categories'
    | '/contacts'
    | '/coupons'
    | '/leads'
    | '/login'
    | '/media'
    | '/navigation'
    | '/orders'
    | '/pages'
    | '/portfolios'
    | '/posts'
    | '/products'
    | '/profile'
    | '/redirects'
    | '/settings'
    | '/tags'
    | '/categories/$categoryId'
    | '/coupons/$couponId'
    | '/media/$mediaId'
    | '/orders/$orderId'
    | '/pages/$pageId'
    | '/portfolios/$portfolioId'
    | '/posts/$postId'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/categories'
    | '/contacts'
    | '/coupons'
    | '/leads'
    | '/login'
    | '/media'
    | '/navigation'
    | '/orders'
    | '/pages'
    | '/portfolios'
    | '/posts'
    | '/products'
    | '/profile'
    | '/redirects'
    | '/settings'
    | '/tags'
    | '/categories/$categoryId'
    | '/coupons/$couponId'
    | '/media/$mediaId'
    | '/orders/$orderId'
    | '/pages/$pageId'
    | '/portfolios/$portfolioId'
    | '/posts/$postId'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  CouponsRoute: typeof CouponsRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRouteWithChildren
  NavigationRoute: typeof NavigationRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PagesRoute: typeof PagesRouteWithChildren
  PortfoliosRoute: typeof PortfoliosRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RedirectsRoute: typeof RedirectsRoute
  SettingsRoute: typeof SettingsRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirects': {
      id: '/redirects'
      path: '/redirects'
      fullPath: '/redirects'
      preLoaderRoute: typeof RedirectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/portfolios/$portfolioId': {
      id: '/portfolios/$portfolioId'
      path: '/$portfolioId'
      fullPath: '/portfolios/$portfolioId'
      preLoaderRoute: typeof PortfoliosPortfolioIdRouteImport
      parentRoute: typeof PortfoliosRoute
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof PagesRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/media/$mediaId': {
      id: '/media/$mediaId'
      path: '/$mediaId'
      fullPath: '/media/$mediaId'
      preLoaderRoute: typeof MediaMediaIdRouteImport
      parentRoute: typeof MediaRoute
    }
    '/coupons/$couponId': {
      id: '/coupons/$couponId'
      path: '/$couponId'
      fullPath: '/coupons/$couponId'
      preLoaderRoute: typeof CouponsCouponIdRouteImport
      parentRoute: typeof CouponsRoute
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface CouponsRouteChildren {
  CouponsCouponIdRoute: typeof CouponsCouponIdRoute
}

const CouponsRouteChildren: CouponsRouteChildren = {
  CouponsCouponIdRoute: CouponsCouponIdRoute,
}

const CouponsRouteWithChildren =
  CouponsRoute._addFileChildren(CouponsRouteChildren)

interface MediaRouteChildren {
  MediaMediaIdRoute: typeof MediaMediaIdRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaMediaIdRoute: MediaMediaIdRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface PagesRouteChildren {
  PagesPageIdRoute: typeof PagesPageIdRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesPageIdRoute: PagesPageIdRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface PortfoliosRouteChildren {
  PortfoliosPortfolioIdRoute: typeof PortfoliosPortfolioIdRoute
}

const PortfoliosRouteChildren: PortfoliosRouteChildren = {
  PortfoliosPortfolioIdRoute: PortfoliosPortfolioIdRoute,
}

const PortfoliosRouteWithChildren = PortfoliosRoute._addFileChildren(
  PortfoliosRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactsRoute: ContactsRoute,
  CouponsRoute: CouponsRouteWithChildren,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRouteWithChildren,
  NavigationRoute: NavigationRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PagesRoute: PagesRouteWithChildren,
  PortfoliosRoute: PortfoliosRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RedirectsRoute: RedirectsRoute,
  SettingsRoute: SettingsRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
